name = "PolygonAlgorithms"
uuid = "32a0d02f-32d9-4438-b5ed-3a2932b48f96"
authors = ["Lior Sinai <sinailior@gmail.com>"]
version = "0.4.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]